name: uts1
description: "Aplikasi resep makanan."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0  # Ditambahkan untuk menyimpan data resep favorit
  provider: ^6.0.5          # Ditambahkan untuk state management
  http: ^0.13.6
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^8.0.0
  image_picker: ^1.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Tambahkan ini untuk mengakses gambar
  assets:
    - assets/images/
